### PR TITLE
[Not Finished] Submit eyes at the same time.

### PR DESCRIPTION
**Pull request by zurgeg**
As the title says, this is an Unfinished PR to submit the eyes at the same time. The particular thing I couldn't figure out how to do is replacing `self.right_cb` in the right eye setup.

### CODE REVIEW

**Comment by el-dee** [comment]
With this modification you no longer render the left-eye. Both callbacks must be kept, however both eye textures must be send in the right eye cb. The problem is that the left eye texture is no longer bound and so contains garbage if I remember correctly.

We must find a way to keep the left eye texture bound while the right eye is rendered. 

If that's not possible, a common texture must be used for both eyes and rendered in Side-by-Side mode. The display region must be configured to use only half of the texture. And when the eyes are submitted the correct boundaries must also be sent.

As I said I don't have time to work on this right know but probably next week I should find some free time to test it.

**Comment by zurgeg** [comment]
@el-dee Well, I went ahead and grabbed an example from `pyopenvr` and took a look at it (because I remember it having single-pass rendering) and it looks like it just does this:
```
        self.compositor.submit(vr.Eye_Left, self.texture)
        self.compositor.submit(vr.Eye_Right, self.texture)
```
Note that this problem is absent in this sample code, meaning that we should be able to fix this easily.
In case you're wondering what `self.texture` is, it's simply defined by the following:
```
        self.texture = vr.Texture_t()
        self.texture.handle = self.texture_id
        self.texture.eType = vr.TextureType_OpenGL
        self.texture.eColorSpace = vr.ColorSpace_Gamma
```

**Comment by el-dee** [comment]
I know this code quite well :) The problem is this is only an example that use raw OpenGL to perform the rendering, so it has full control over the framebuffer creation, texture binding, ...  The field handle of the vr_texture_t object is the handle given by OpenGL when you bind a texture in the graphic card. This handle must be valid until the texture is submitted to OpenVR. As this is only a simple example, the code has no problem keeping the texture bound

When rendering the scene using Panda3D (or any other high level 3D engine), you don't have control over the texture binding, the frame buffer lifetime, and so on. So you must adapt the code to this fact. Hence my previous remark about find ing a way to keep the left eye texture bound until the right eye is fully rendered or instead use SBS rendering into a common texture.

**Comment by el-dee** [comment]
Fixed in https://github.com/el-dee/panda3d-openvr/commit/7d2d9d392aad0bc7885edc3e1733c541493cbd71 Thank you for your help.

**Pull request closed without merging**
