### PR TITLE
Add skeletal input support [WIP, Not tested!!]

### PR DESCRIPTION
**Pull request by zurgeg**
I just copied code from Valve's samples and modified the functions above it, hopefully this works ^^)

### CODE REVIEW

**Comment by el-dee** [comment]
Thanks, it looks like a really interesting addition !

**Comment by zurgeg** [comment]
Alrighty, so I got further on this:
```
    def get_skelatal_action_value(self,action,device_path=None):
        bone_transform = openvr.VRBoneTransform_t()
        print(dir(bone_transform))
        skeleton_data = self.vr_input.getSkeletalActionData(action)
        bone_data = self.vr_input.getSkeletalBoneData(action, openvr.VRSkeletalTransformSpace_Parent, openvr.VRSkeletalMotionRange_WithoutController, bone_transform)
        
        if device_path is not None:
            if skeleton_data.bActive:
                origin_info = self.vr_input.getOriginTrackedDeviceInfo(skeleton_data.activeOrigin)
                device_path = origin_info.devicePath
        if skeleton_data.bActive:
            return bone_transform, device_path
        else:
            return None, None
```
Except it kicks out something along the lines of "No Input"
I'll have to collet the exact error. @el-dee Do you know what this means?
EDIT: `openvr.error_code.InputError_NoData`

**Comment by el-dee** [comment]
I believe this is because your input is not properly linked with the source of data.

You need to define actions for each skeleton, e.g. :

```json
    {
      "name": "/actions/default/in/SkeletonLeftHand",
      "type": "skeleton",
      "skeleton": "/skeleton/hand/left"
    },
    {
      "name": "/actions/default/in/SkeletonRightHand",
      "type": "skeleton",
      "skeleton": "/skeleton/hand/right"
    },
``` 

Then in your binding file, map the skeleton entries with the defined action (or use the SteamVR Binding UI):

```json
      "skeleton": [
        {
          "output": "/actions/default/in/SkeletonLeftHand",
          "path": "/user/hand/left/input/skeleton/left"
        },
        {
          "output": "/actions/default/in/SkeletonRightHand",
          "path": "/user/hand/right/input/skeleton/right"
        }
      ]
```

**Comment by zurgeg** [comment]
Will take a look later, don't you have to do the same thing to
/skeleton/hand/right that you do with /user/hand/right in the code?

**Comment by zurgeg** [comment]
Update, with the following binds:
```
{
  "default_bindings": [{
	    "controller_type": "knuckles",
	    "binding_url": "index_binds.json"
	}
   ],
   "action_sets" : [
      {
         "name" : "/actions/main",
         "usage" : "leftright"
      }
   ],
   "actions" : [
      {
         "name" : "/actions/main/in/Select",
         "requirement" : "mandatory",
         "type" : "boolean"
      },
      {
         "name": "/actions/main/in/trackpadclick",
         "type": "boolean"
      },
      {
         "name": "/actions/main/in/trackpadpos",
         "type": "vector2"
      },
      {
         "name" : "/actions/main/out/Haptic",
         "type" : "vibration"
      },
      {
         "name" : "/actions/main/in/RightHand",
         "type" : "pose"
      },
      {
         "name" : "/actions/main/in/RightHandSkeleton",
         "skeleton" : "/skeleton/hand/right",
         "type" : "skeleton"
      }
   ],
   "localization" : [
      {
         "/actions/main" : "ViiR No Ma",
         "/actions/main/in/Select" : "Select",
         "/actions/main/in/RightHand" : "Right Hand Position",
         "/actions/main/in/RightHandSkeleton" : "Right Hand Skeleton",
         "/actions/main/out/Haptic" : "Haptic",
         "/actions/main/in/trackpadclick" : "Trackpad Click",
         "/actions/main/in/trackpadpos" : "Trackpad Move",
         "language_tag" : "en_us"
      }
   ]
}
```
I now get the following traceback:
```
Traceback (most recent call last):
  File "C:\Users\zurgE\OneDrive\Documents\ViiR No Ma\hand_test_suite.py", line 24, in update_poses_task
    self.update_action_state()
  File "C:\Users\zurgE\OneDrive\Documents\ViiR No Ma\p3dopenvr_skeleton_patch\p3dopenvr.py", line 287, in update_action_state
    self.update_action()
  File "C:\Users\zurgE\OneDrive\Documents\ViiR No Ma\hand_test_suite.py", line 50, in update_action
    skel = self.get_skelatal_action_value(self.action_skeleton)
  File "C:\Users\zurgE\OneDrive\Documents\ViiR No Ma\p3dopenvr_skeleton_patch\p3dopenvr.py", line 396, in get_skelatal_action_value
    bone_data = self.vr_input.getSkeletalBoneData(action, openvr.VRSkeletalTransformSpace_Parent, openvr.VRSkeletalMotionRange_WithoutController, bone_transform)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openvr\__init__.py", line 6745, in getSkeletalBoneData
    openvr.error_code.InputError.check_error_value(error)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openvr\error_code\__init__.py", line 23, in check_error_value
    raise error_class(error_value, message)
openvr.error_code.InputError_InvalidBoneCount
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    App().run()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\showbase\ShowBase.py", line 3325, in run
    self.taskMgr.run()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\task\Task.py", line 541, in run
    self.step()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\direct\task\Task.py", line 495, in step
    self.mgr.poll()
  File "C:\Users\zurgE\OneDrive\Documents\ViiR No Ma\hand_test_suite.py", line 24, in update_poses_task
    self.update_action_state()
  File "C:\Users\zurgE\OneDrive\Documents\ViiR No Ma\p3dopenvr_skeleton_patch\p3dopenvr.py", line 287, in update_action_state
    self.update_action()
  File "C:\Users\zurgE\OneDrive\Documents\ViiR No Ma\hand_test_suite.py", line 50, in update_action
    skel = self.get_skelatal_action_value(self.action_skeleton)
  File "C:\Users\zurgE\OneDrive\Documents\ViiR No Ma\p3dopenvr_skeleton_patch\p3dopenvr.py", line 396, in get_skelatal_action_value
    bone_data = self.vr_input.getSkeletalBoneData(action, openvr.VRSkeletalTransformSpace_Parent, openvr.VRSkeletalMotionRange_WithoutController, bone_transform)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openvr\__init__.py", line 6745, in getSkeletalBoneData
    openvr.error_code.InputError.check_error_value(error)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\openvr\error_code\__init__.py", line 23, in check_error_value
    raise error_class(error_value, message)
openvr.error_code.InputError_InvalidBoneCount
```
@el-dee Do you have any idea what this could mean and how it could be fixed?

**Comment by zurgeg** [comment]
Update, after a long time of messing with this, I sorta(?) got it to work. The only problem is when applying the rotation to the hand, nothing happens. Valve provides an `enum` with all of the bones:
```cpp
typedef int32_t BoneIndex_t;
const BoneIndex_t INVALID_BONEINDEX = -1;
enum HandSkeletonBone : BoneIndex_t
{
	eBone_Root = 0,
	eBone_Wrist,
	eBone_Thumb0,
	eBone_Thumb1,
	eBone_Thumb2,
	eBone_Thumb3,
	eBone_IndexFinger0,
	eBone_IndexFinger1,
	eBone_IndexFinger2,
	eBone_IndexFinger3,
	eBone_IndexFinger4,
	eBone_MiddleFinger0,
	eBone_MiddleFinger1,
	eBone_MiddleFinger2,
	eBone_MiddleFinger3,
	eBone_MiddleFinger4,
	eBone_RingFinger0,
	eBone_RingFinger1,
	eBone_RingFinger2,
	eBone_RingFinger3,
	eBone_RingFinger4,
	eBone_PinkyFinger0,
	eBone_PinkyFinger1,
	eBone_PinkyFinger2,
	eBone_PinkyFinger3,
	eBone_PinkyFinger4,
	eBone_Aux_Thumb,
	eBone_Aux_IndexFinger,
	eBone_Aux_MiddleFinger,
	eBone_Aux_RingFinger,
	eBone_Aux_PinkyFinger,
	eBone_Count
};
```
Now I would assume this means that `eBone_Thumb0` would correspond to `finger_thumb_0_(l/r)` in the model and would be index 2 in the returned data. Except it apparently doesn't, as I don't see any movement.

So I set up a logging system to log the rotation, like so:
```python
        def update_action():
        #...
       skel = self.get_skelatal_action_value(self.action_skeleton)
        #...
        bone_rot = []
        for i in range(len(self.bones)):
            bone = skel[i] # Grab bone data
            bone_rot_data = skel[i].orientation
            bone_xyzw = (bone_rot_data.x, bone_rot_data.y, bone_rot_data.z, bone_rot_data.w)
            bone_hpr = quaternion_to_euler(*bone_xyzw)
            print(str(i) + ':', bone_hpr)
            self.bones[i].setHpr(*bone_hpr)
```
Do you have any idea why nothing could be happening?

**Comment by zurgeg** [comment]
@el-dee Alright, so in theory(?) this should be ready for merge, all I need is a sample to go with it, and then it should be good to go.

**Comment by zurgeg** [comment]
Upon trying without any bone rotation, the hand appears to be upside down and backward?
image
Are any other transforms being applied to the hand?

**Comment by el-dee** [comment]
Panda3D default coordinates system is Zup, perhaps your model must be converted to have the right orientation. 

Also, the transform matrices received from OpenVR should also be converted. This can be done using the coordinates change matrix already used for the poses.

**Comment by zurgeg** [comment]
What does that mean? Do I take the Transform struct and use set_matrix @el-dee?

**Comment by el-dee** [comment]
I believe the bone transform matrices should be converted with something similar as the `get_pose_modelview()` method.

This will convert the format of the matrices and change the coordinate system.

**Comment by zurgeg** [comment]
@el-dee The `get_pose_modelview()` function uses `convert_mat` which requires said object to have an `m` attribute, the `HmdVector4_t` (for bone position) or the `HmdQuaternionf_t` (for bone rotation) does not have this.

From what I can see, the latter (which is the more important one) contains XYZW attributes, but these do not seem to do anything (except mess up the fingers they are applied to by bending them back) when converted to Euler...

Edit: [This](https://github.com/ValveSoftware/openvr/wiki/Hand-Skeleton#units-and-coordinate-system) looks as if something is wrong, but I can't tell what 🤔

**Comment by zurgeg** [comment]
UPDATE: While reading through the Steam**VR** docs,  it looks like SteamVR uses Y-Up, completely overlooked that LOL

**Comment by zurgeg** [comment]
> Upon trying without any bone rotation, the hand appears to be upside down and backward?
> image
> Are any other transforms being applied to the hand?

Update: This happens when the Armatures get deleted? Are they not getting exported right or something? @el-dee You probably know more about the internals of EGG and the like, maybe you could figure it out?

**Comment by el-dee** [comment]
Would you mind sending me the hand model used (you can send it privately if you want) I will try to find the issue and merge this.

**Comment by zurgeg** [comment]
@el-dee Sure! They have magically appeared on your PC at:
`C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels\vr_glove\vr_glove_right_model.glb` and `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\rendermodels\vr_glove\vr_glove_left_model.glb` (as long as you have Steam and SteamVR installed in the default directories)

**Comment by el-dee** [comment]
It took much longer than I expected until I discovered that the real problem was that the .fbx model is either not a valid .fbx model or is incompatible with how Panda3D manage control joints. 
Commit e444e56 contains the new method to retrieve the skeleton transforms, a helper class to apply those transform onto the control joints of a model and a new sample.

hands

I will add a couple of other helper classes to manage the hands in the next days and I intent to clean up a bit the API before doing a new release.

Also, note that the .glb models from SteamVR are not properly loaded by panda3d-gltf. A workaround is to load them in a 3D tool and save them again. I used https://blackthread.io/gltf-converter/ for that.

**Pull request closed without merging**
